# House Prices Project
Author: Christian Kapp
Description:
This project will take you through my submission for the kaggle project "House Prices: Advanced Regression Techniques" which can be found here:
https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data
The goal of the project is to accurately predict the final price of each home based on the given variables.

In [1]:
# import various libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
%matplotlib inline

In [4]:
# import train & test files
train = pd.read_csv("input/train.csv")
test = pd.read_csv("input/test.csv")

In [7]:
# let's see what the train data set looks like
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal